/**
 * (c) Copyright by Abraxas Informatik AG
 *
 * For license information see LICENSE file.
 */

export enum PersonAttributeEnum {
  vn = 'vn',
  officialName = 'officialName',
  firstName = 'firstName',
  sex = 'sex',
  dateOfBirth = 'dateOfBirth',
  originalName = 'originalName',
  allianceName = 'allianceName',
  aliasName = 'aliasName',
  otherName = 'otherName',
  callName = 'callName',
  languageOfCorrespondence = 'languageOfCorrespondence',
  religion = 'religion',
  restrictedVotingAndElectionRightFederation = 'restrictedVotingAndElectionRightFederation',
  countryNameShort = 'countryNameShort',
  municipalityName = 'municipalityName',
  municipalityId = 'municipalityId',
  typeOfResidence = 'typeOfResidence',
  residencePermit = 'residencePermit',
  residencePermitValidFrom = 'residencePermitValidFrom',
  residencePermitValidTill = 'residencePermitValidTill',
  residenceEntryDate = 'residenceEntryDate',
  contactAddressExtensionLine1 = 'contactAddressExtensionLine1',
  contactAddressExtensionLine2 = 'contactAddressExtensionLine2',
  contactAddressStreet = 'contactAddressStreet',
  contactAddressHouseNumber = 'contactAddressHouseNumber',
  contactAddressPostOfficeBoxText = 'contactAddressPostOfficeBoxText',
  contactAddressPostOfficeBoxNumber = 'contactAddressPostOfficeBoxNumber',
  contactAddressLine1 = 'contactAddressLine1',
  contactAddressLine2 = 'contactAddressLine2',
  contactAddressLine3 = 'contactAddressLine3',
  contactAddressLine4 = 'contactAddressLine4',
  contactAddressLine5 = 'contactAddressLine5',
  contactAddressLine6 = 'contactAddressLine6',
  contactAddressLine7 = 'contactAddressLine7',
  contactAddressTown = 'contactAddressTown',
  contactAddressLocality = 'contactAddressLocality',
  contactAddressZipCode = 'contactAddressZipCode',
  residenceAddressExtensionLine1 = 'residenceAddressExtensionLine1',
  residenceAddressExtensionLine2 = 'residenceAddressExtensionLine2',
  residenceAddressStreet = 'residenceAddressStreet',
  residenceAddressHouseNumber = 'residenceAddressHouseNumber',
  residenceAddressPostOfficeBoxText = 'residenceAddressPostOfficeBoxText',
  residenceAddressTown = 'residenceAddressTown',
  residenceCountry = 'residenceCountry',
  residenceAddressZipCode = 'residenceAddressZipCode',
  moveInArrivalDate = 'moveInArrivalDate',
  moveInMunicipalityName = 'moveInMunicipalityName',
  moveInCantonAbbreviation = 'moveInCantonAbbreviation',
  moveInComesFrom = 'moveInComesFrom',
  moveInCountryNameShort = 'moveInCountryNameShort',
  moveInUnknown = 'moveInUnknown',
  hasValidationErrors = 'hasValidationErrors',
  sendVotingCardsToDomainOfInfluenceReturnAddress = 'sendVotingCardsToDomainOfInfluenceReturnAddress',
  eVoting = 'eVoting',
  isHouseholder = 'isHouseholder',
  residenceBuildingId = 'residenceBuildingId',
  residenceApartmentId = 'residenceApartmentId'
}
