/**
 * (c) Copyright by Abraxas Informatik AG
 *
 * For license information see LICENSE file.
 */

import { InjectionToken } from '@angular/core';

export const constants = {
  TRANSLATION_KEY_SAVE_SUCCESSFUL_MESSAGE: 'SHARED_SAVE_SUCCESSFUL',
  TRANSLATION_KEY_DELETE_SUCCESSFUL_MESSAGE: 'SHARED_DELETE_SUCCESSFUL',
  TRANSLATION_KEY_UNDERSTOOD: 'SHARED_ACTION_UNDERSTOOD',
  TRANSLATION_KEY_FILL_ALL_REQUIRED_FIELDS_MESSAGE: 'SHARED_FILL_ALL_REQUIRED_FIELDS_MESSAGE',
  TRANSLATION_KEY_PAGE_LEAVE_SAVE_ENTRIES_TITLE: 'SHARED_PAGE_LEAVE_SAVE_ENTRIES_DIALOG_TITLE',
  TRANSLATION_KEY_PAGE_LEAVE_SAVE_ENTRIES_CONTENT: 'SHARED_PAGE_LEAVE_SAVE_ENTRIES_DIALOG_CONTENT',
  TRANSLATION_KEY_PAGE_LEAVE_SAVE_ENTRIES_CONFIRM_BUTTON:
    'SHARED_PAGE_LEAVE_SAVE_ENTRIES_DIALOG_CONFIRM_BUTTON',
  TRANSLATION_KEY_PAGE_LEAVE_SAVE_ENTRIES_CANCEL_BUTTON:
    'SHARED_PAGE_LEAVE_SAVE_ENTRIES_DIALOG_CANCEL_BUTTON',
  TRANSLATION_KEY_YEARLY: 'SHARED_YEARLY',
  TRANSLATION_KEY_HALFYEARLY: 'SHARED_HALFYEARLY',
  TRANSLATION_KEY_QUARTERYEARLY: 'SHARED_QUARTERYEARLY',
  TRANSLATION_KEY_MONTHLY: 'SHARED_MONTHLY',
  EMPTY_GUID: '00000000-0000-0000-0000-000000000000',
  PAGES_BACK_NAVIGATION_SESSION_STORAGE_LEY: 'pages-back-navigation',
  SESSION_STORAGE_SELECTED_VALUE_CACHE_TEMPLATE: 'voting-stimmregister:{tenant-id}-{key}',
};

export const CONTAINER_DATA = new InjectionToken<{}>('CONTAINER_DATA');
