/**
 * (c) Copyright by Abraxas Informatik AG
 *
 * For license information see LICENSE file.
 */

// The language JSON have to match these keys for correct translations of the labels
export enum FilterCriteriaReferenceId {
  vn = 'vn',
  municipalityId = 'municipalityId',
  restrictedVotingAndElectionRightFederation = 'restrictedVotingAndElectionRightFederation',
  age = 'age',
  swissCitizenship = 'swissCitizenship',
  municipalityName = 'municipalityName',
  officialName = 'officialName',
  firstName = 'firstName',
  religion = 'religion',
  country = 'country',
  eVoting = 'eVoting',
  sex = 'sex',
  dateOfBirth = 'dateOfBirth',
  dateOfBirthAdjusted = 'dateOfBirthAdjusted',
  originalName = 'originalName',
  allianceName = 'allianceName',
  aliasName = 'aliasName',
  otherName = 'otherName',
  callName = 'callName',
  typeOfResidence = 'typeOfResidence',
  originName1_7 = 'originName1_7',
  originOnCanton1_7 = 'originOnCanton1_7',
  residencePermit = 'residencePermit',
  residencePermitValidFrom = 'residencePermitValidFrom',
  residencePermitValidTill = 'residencePermitValidTill',
  residenceEntryDate = 'residenceEntryDate',
  contactAddressExtensionLine1 = 'contactAddressExtensionLine1',
  contactAddressExtensionLine2 = 'contactAddressExtensionLine2',
  contactAddressStreet = 'contactAddressStreet',
  contactAddressHouseNumber = 'contactAddressHouseNumber',
  contactAddressPostOfficeBoxText = 'contactAddressPostOfficeBoxText',
  contactAddressLine1_7 = 'contactAddressLine1_7',
  contactAddressTown = 'contactAddressTown',
  contactAddressLocality = 'contactAddressLocality',
  contactAddressZipCode = 'contactAddressZipCode',
  residenceAddressExtensionLine1 = 'residenceAddressExtensionLine1',
  residenceAddressExtensionLine2 = 'residenceAddressExtensionLine2',
  residenceAddressStreet = 'residenceAddressStreet',
  residenceAddressHouseNumber = 'residenceAddressHouseNumber',
  residenceAddressPostOfficeBoxText = 'residenceAddressPostOfficeBoxText',
  residenceAddressTown = 'residenceAddressTown',
  residenceAddressZipCode = 'residenceAddressZipCode',
  moveInArrivalDate = 'moveInArrivalDate',
  moveInMunicipalityName = 'moveInMunicipalityName',
  moveInCantonAbbreviation = 'moveInCantonAbbreviation',
  moveInComesFrom = 'moveInComesFrom',
  moveInCountryNameShort = 'moveInCountryNameShort',
  moveInUnknown = 'moveInUnknown',
  politicalCircleId = 'politicalCircleId',
  politicalCircleName = 'politicalCircleName',
  catholicCircleId = 'catholicCircleId',
  catholicCircleName = 'catholicCircleName',
  evangelicCircleId = 'evangelicCircleId',
  evangelicCircleName = 'evangelicCircleName',
  schoolCircleId = 'schoolCircleId',
  schoolCircleName = 'schoolCircleName',
  trafficCircleId = 'trafficCircleId',
  trafficCircleName = 'trafficCircleName',
  residentialDistrictCircleId = 'residentialDistrictCircleId',
  residentialDistrictCircleName = 'residentialDistrictCircleName',
  peopleCircleId = 'peopleCircleId',
  peopleCircleName = 'peopleCircleName',
  hasValidationErrors = 'hasValidationErrors',
  sendVotingCardsToDomainOfInfluenceReturnAddress = 'sendVotingCardsToDomainOfInfluenceReturnAddress',
  isHouseholder = 'isHouseholder',
  residenceBuildingId = 'residenceBuildingId',
  residenceApartmentId = 'residenceApartmentId',
}
